### PR TITLE
Typo "Azure Storage explorer"→"Azure Storage Explorer"

### PR DESCRIPTION
**Pull request by hyoshioka0128**
## Purpose

* Typo "Azure Storage explorer"→"Azure Storage Explorer"
 https://docs.microsoft.com/en-us/samples/azure-samples/storage-blobs-node-quickstart/storage-blobs-node-quickstart/

## Does this introduce a breaking change?

```
[ ] Yes
[x] No
```

## Pull Request Type
What kind of change does this Pull Request introduce?

```
[ ] Bugfix
[ ] Feature
[x] Code style update (formatting, local variables)
[ ] Refactoring (no functional changes, no api changes)
[ ] Documentation content changes
[ ] Other... Please describe:
```

### CODE REVIEW

**Comment by hyoshioka0128** [comment]
@TinaMcN Could you please explain a bit more about the reason of PR not being built? Thanks.

**Comment by hyoshioka0128** [comment]
@TinaMcN @SunnyDeng Could you please explain a bit more about the reason of PR not being built? Thanks.

**Comment by SunnyDeng** [comment]
+ @ramya-rao-a who own this repo

**Review by ramya-rao-a — APPROVED** [review]

**Comment by ramya-rao-a** [comment]
@tamram,
Can you merge this PR if it looks good to you?

**Pull request merged**
